---
title: "p8105_hw5_scs2267.Rmd"
output: github_document
date: "2024-11-15"
---

```{r}
library(tidyverse)
library(readr)
set.seed(1)
```

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1


```{r}
bday_sim = function(n) {

  bdays = sample(1:365, size = n, replace = TRUE)
  
  duplicate = length(unique(bdays)) < n

  return(duplicate)
  
}

bday_sim(10)
```

# Problem 2

## Mean of Zero


```{r}
sim_mean_sd = function(n = 30, mu, sd = 5) {
  
sim_data = rnorm(n, mu, sd)
  
test = t.test(sim_data, y=NULL, alternative = c("two.sided"), mu = mu) %>% broom::tidy() %>% 
  janitor::clean_names() %>% 
  select(p_value, estimate)
  
  out_df = tibble(
    true_mean = mu,
    p_value = test$p_value,
    e_mean = test$estimate
  )
  
  return(out_df)
}
```

```{r}
output = vector("list", 5000)

for (i in 1:5000) {
  
  output[[i]] = sim_mean_sd(30, 0, 5)
  
}

sim_results = bind_rows(output)
```

## Means 1-6

```{r}
sim_res = 
  expand_grid(
    mu = c(1, 2, 3, 4, 5, 6),
    iter = 1:5000
  ) %>%  
  mutate(samp_res = map(mu, \(x) sim_mean_sd(n = 30, x, sd = 5))) %>%  
  unnest(samp_res) %>% 
  select(true_mean, p_value, e_mean)
```

## Plot 1

```{r}
power_results = sim_res %>%
  group_by(true_mean) %>% 
  summarize(
    power = mean(p_value < 0.05)
  )
power_results %>% 
  ggplot(aes(x = true_mean, y = power))+
  geom_line()
```

## Plot 2
```{r}

```



# Problem 3
```{r}

```

